Deck.create(name: "Beer Styles", num_of_cards: 6)
Card.create(question: "What does IPA stand for?", answer: "India Pale Ale", deck_id: 1)
Card.create(question: "What style is Guiness?", answer: "Stout", deck_id: 1)
Card.create(question: "What German sour beer is traditionally brewed with salt?", answer: "Gose", deck_id: 1)
Card.create(question: "This style is usually efferscent and has flavors reminiscent of banana.", answer: "Hefeweizen", deck_id: 1)
Card.create(question: "Delirium Tremens is one of these.", answer: "Tripel", deck_id: 1)
Card.create(question: "This style is big, boozy and can age very well; think Sierra Nevada BigFoot", answer: "American Barleywine", deck_id: 1)


Deck.create(name: "Wine Facts", num_of_cards: 12)
Card.create(question: "Which of the following is NOT a grape varietal?  Pinot Noir, Gewurtztraminer, Petite Poubelle, Muscat", answer: "petite poubelle", deck_id: 2)
Card.create(question: "In what country would you find the Tempranillo grape?", answer: "spain", deck_id: 2)
Card.create(question: "True or false: Petite Sirah is just another name for Syrah (Shiraz)", answer: "false", deck_id: 2)
Card.create(question: "What kind of grape is used for a Sauvignon Blanc", answer: "sauvignon blanc", deck_id: 2)
Card.create(question: "Rudolf Steiner was an Austrian philosopher who was very excited about vineyards' ecosystems. His ideas gave rise to what classification of wine?", answer: "biodynamic", deck_id: 2)
Card.create(question: "What region is home to Cabernet Sauvignon grapes?", answer: "bordeaux", deck_id: 2)
Card.create(question: "What country is home to Nebbiolo?", answer: "italy", deck_id: 2)
Card.create(question: "It's rumored that Sting drinks bottles of this type of wine during concerts", answer: "rose", deck_id: 2)
Card.create(question: "In what region MUST your vineyard be in order to make Barolo?", answer: "piedmont", deck_id: 2)
Card.create(question: "Rosé most commonly comes from what region in France?", answer: "provence", deck_id: 2)
Card.create(question: "Which grape does NOT go into making Cabernet Sauvignon?  Cabernet Franc, Sauvignon Blanc, Grenache", answer: "grenache", deck_id: 2)
Card.create(question: "What kind of grapes is White Burgundy?", answer: "chardonnay", deck_id: 2)

Deck.create(name:"Beer History", num_of_cards: 6)
Card.create(question: "What precious stone was immersed in beer to test its authenticity in the early 1900s?" , answer: "diamonds", deck_id: 3)
Card.create(question: "The oldest brewery in America started in 1809.  (True or false?)", answer: "false", deck_id: 3)
Card.create(question: "How many breweries in America survived Prohibition? (60, 160 or 260?)", answer: "160", deck_id: 3)
Card.create(question: "In the middle ages, monks used mortar mixed with ale to build churches and monasteries.  (True or false?)", answer: "true", deck_id: 3)
Card.create(question: "Which U.S. president established his own brewhouse?", answer: "george washington", deck_id: 3)
Card.create(question: "Louis Pasteur experimented with beer before milk. (True or false?)", answer: "true", deck_id: 3)

Deck.create(name:"Liquor Facts", num_of_cards: 6)
Card.create(question:"Where does gin get much of its flavor from?", answer: "juniper berry", deck_id: 4)
Card.create(question: "Tequila is made from what plant?", answer: "blue agave", deck_id: 4)
Card.create(question: "What liquor is the most popular worldwide?", answer: "vodka", deck_id: 4)
Card.create(question: "The British used gin as an antiseptic to treat what disease?", answer: "malaria", deck_id: 4)
Card.create(question: "True or false: The sidecar was invented during the Prohibition era to mask the flavor of poorly-made alcohol",
answer: "true", deck_id: 4)
Card.create(question: "A martini becomes a Gibson by adding what to it?", answer: "onion", deck_id: 4)

